# Generated by Django 5.1.2 on 2024-12-04 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveventapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=50)),
                ('cus_phone', models.CharField(max_length=12)),
                ('booked_on', models.DateField(auto_now=True)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eveventapp.event')),
            ],
        ),
    ]
